@startuml C4_Containers_SmartHome
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/refs/heads/master/C4_Container.puml
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons

!include DEVICONS/react.puml
!include DEVICONS/postgresql.puml
!include DEVICONS/go.puml
!include DEVICONS/dotnet.puml

title Диаграмма контейнеров (C4 Level 2) — экосистема "Умный посёлок"

LAYOUT_WITH_LEGEND()
LAYOUT_TOP_DOWN()

Person(homeowner, "Владелец дома", "Пользователь системы")
Person(support, "Саппорт", "Техническая поддержка")

System_Boundary(system, "SmartHome system") {
    Container(spa, "SPA", "React", "Веб-интерфейс для пользователя системы", $sprite="react")
    Container(spaAdmin, "SPA Admin", "React", "Веб-интерфейс для технической поддержки", $sprite="react")
    Container(apiGateway, "API Gateway", "Go", "Промежуточный API между веб-интерфейсом и внутренними микросервисами", $sprite="go")
    Container(users, "Users", ".NET", "Микросервис управления пользователями и списком их домов", $sprite="dotnet")
    Container(devices, "Devices", ".NET", "Микросервис управления устройствами", $sprite="dotnet")
    Container(telemetry, "Telemetry", "Go", "Микросервис телеметрии", $sprite="go")

    ContainerDb(db, "Main database", "PostgreSQL", "Основная база приложения", $sprite="postgresql")
    ContainerDb(telemetryDb, "Telemetry database", "Clickhouse", "Хранит телеметрию устройств")
    ContainerQueue(telemetryQueue, "Telemetry queue", "RabbitMQ", "Очередь отправки телеметрии")
}

Container_Ext(partnerDevicesApi, "Partners devices API", "API устройств партнёров")

Rel(homeowner, spa, "Uses", "https")
Rel(support, spaAdmin, "Uses", "https")
Rel(spa, apiGateway, "Uses", "https")
Rel(spaAdmin, apiGateway, "Uses", "https")
Rel(apiGateway, users, "Fetches/updates users & auth info", "https")
Rel(apiGateway, devices, "Devices CRUD", "https")
Rel(apiGateway, telemetry, "Fetches telemetry for displaying to user", "https")

Rel(users, db, "Reads/Writes users info")

Rel(devices, db, "Reads/Writes devices")

Rel(devices, partnerDevicesApi, "Fetches devices data/sends commands")

Rel(devices, telemetryQueue, "Writes")
Rel(telemetryQueue, telemetry, "Sends")
Rel(telemetry, telemetryDb, "Reads/Writes")

